pipeline:
  publish-private:
    image: plugins/docker
    repo: registry.paradas.co/do-dns-updater
    registry: registry.paradas.co
    secrets: [ docker_username, docker_password ]
    tags:
      - latest
      - build-${DRONE_BUILD_NUMBER}
  publish-api-docker:
    image: plugins/docker
    username: ${DOCKERHUB_USERNAME}
    password: ${DOCKERHUB_PASSWORD}
    email: ${DOCKERHUB_EMAIL}
    repo: jparadasb/do-dns-updater
    tags:
      - latest
      - build-${DRONE_BUILD_NUMBER}